### PR TITLE
XRC721 how to using Truffle

### PR DESCRIPTION
**Pull request by yash0501**
This PR is in response the issue #35

### CODE REVIEW

**Comment by WalterBlueu** [comment]
I am getting an error on the "import" commands in the XRC721.sol file:

image

image

Not sure what steps are to fix this issue.

**Comment by mogithehurt** [comment]
@WalterBlueu  hope you can find your answer here https://stackoverflow.com/questions/67321111/file-import-callback-not-supported

**Comment by yash0501** [comment]
I have updated the code for the contracts. They would work fine now.

**Comment by WalterBlueu** [comment]
@yash0501 thank you, that solved the problem.  We are now up against the same verification issue as we saw with Remix.  Give me a few hours to see if I can get more information on this issue from BlocksScan.

**Comment by WalterBlueu** [comment]
@yash0501 BlocksScan pointed me to this tutorial on flattening the dependencies from OpenZeppelin: https://www.xdc.dev/ivan_blocksscan/learn-how-to-flatten-a-smart-contract-and-verify-on-blocksscan-56on

**Comment by WalterBlueu** [comment]
I don't know if this tool is what you need for Truffle, but it looks like updating the how-to to use a tool like this to flatten the smart contract will get the job done: https://www.npmjs.com/package/truffle-flattener

**Comment by yash0501** [comment]
Okay, I will check it out and try to flatten the smart contract to verify it on blockscan

**Pull request merged**
