### PR TITLE
Add page about Securing your Masternode and associated images

### PR DESCRIPTION
**Pull request by s4njk4n**

### CODE REVIEW

**Comment by s4njk4n** [comment]
Reopened request after formatting images to be centre justified

**Review by MrBlockchain22 — COMMENTED** [review]
I love all the content you are suggesting to add and I believe this will further help anyone currently running a node, and those looking at launching a node in the future. 
I would definitely add a section for testnet so those running testnet nodes are able to follow your guides to better secure their nodes as well.

**Comment by s4njk4n** [comment]
Will do

**Comment by cryptoRREN** [comment]
Great information for anyone deploying any kind of node on the network.

**Review by cryptoRREN — APPROVED** [review]

**Review by cryptoRREN — APPROVED** [review]

**Pull request merged**
