### PR TITLE
contract on XDC using hardhat guide

### PR DESCRIPTION
**Pull request by ArpitaGanatra**

### CODE REVIEW

**Comment by WalterBlueu** [comment]
Hello @ArpitaGanatra , for the how-to article we need access to the code in the .sol file so that people don't have to look at your screenshot and try to copy it.  Could you please refactor your how to article to use the simple solidity Pizza example found [here]?(https://github.com/XDC-Community/docs/tree/main/how-to/Pizza)

**Comment by ArpitaGanatra** [comment]
Hey @WalterBlueu 

I have made the necessary changes. please take a look.

**Comment by WalterBlueu** [comment]
Thank you, I will take a look.

**Comment by WalterBlueu** [comment]
@ArpitaGanatra I am going through the how-to and have received an error on deploy:

image

I believe I am missing setup information for XDC Mainnet.  Here is the contents of my hardhat.config file:

```
require("@nomicfoundation/hardhat-toolbox");
require("dotenv").config({ path: ".env" });

const XINFIN_NETWORK_URL = process.env.XINFIN_NETWORK_URL;
const XINFIN_PRIVATE_KEY = process.env.XINFIN_PRIVATE_KEY;

module.exports = {
  solidity: "0.8.9",
  networks: {
    xinfin: {
      url: XINFIN_NETWORK_URL,
      accounts: [XINFIN_PRIVATE_KEY],
    },
  },
};
```

I am using a throwaway XDCPay account that I created for this how-to, here is my .env file contents:

```
XINFIN_NETWORK_URL=https://erpc.xinfin.network
WALLET_PRIVATE_KEY=myself pulse label credit penalty matrix citizen crowd proud place muffin kingdom
```

**Comment by ArpitaGanatra** [comment]
@WalterBlueu 
In .env, WALLET_PRIVATE_KEY is suppose to have your private key and not the seed phrase.

**Comment by WalterBlueu** [comment]
@ArpitaGanatra can you please update the how-to with explicit steps on how to setup the .env and config files?  I want to make sure that someone without any past dev experience is able to follow this step-by-step and find success.  Thanks for working with me on this.

**Comment by ArpitaGanatra** [comment]
@WalterBlueu made the necessary changes.

**Comment by WalterBlueu** [comment]
I will take a look, thank you!

**Comment by WalterBlueu** [comment]
@ArpitaGanatra I am still seeing the same error:
image

Here is the project directory layout (incase my .env file is at the wrong location):
image


Here is the content of my .env file:
```
XINFIN_NETWORK_URL=https://erpc.xinfin.network
WALLET_PRIVATE_KEY=c46461a489a2a3b9330730560a8da9111b0001a7eb84bfcc1cb37a31dcb86054
```

Here is the content of my hardhat.config file:

```
require("@nomicfoundation/hardhat-toolbox");
require("dotenv").config({ path: ".env" });

const XINFIN_NETWORK_URL = process.env.XINFIN_NETWORK_URL;
const XINFIN_PRIVATE_KEY = process.env.XINFIN_PRIVATE_KEY;

module.exports = {
  solidity: "0.8.9",
  networks: {
    xinfin: {
      url: XINFIN_NETWORK_URL,
      accounts: [XINFIN_PRIVATE_KEY],
    },
  },
};
```

Please let me know if you can identify what I am doing wrong, and update the how-to to reflect.  I appreciate your patience.

**Comment by ArpitaGanatra** [comment]
@WalterBlueu 
You are getting the error of being undefined. 
Here are the possible reasons. 
1)Have you done npm i dotenv as mentioned in the how-to?
2) check if spellings in your hardhat.config.js and .env match.

**Comment by WalterBlueu** [comment]
@ArpitaGanatra I found the typo, in your article you have:
image
it is supposed to be:
image

I am getting a new error message now:
image

Let me know if you know how to address this issue.

**Comment by ArpitaGanatra** [comment]
@WalterBlueu I will change that mistake. Also when I saw the wallet with the private key in your .env it does not have any balance.
`
XINFIN_NETWORK_URL=https://erpc.xinfin.network
XINFIN_PRIVATE_KEY=202e3c9d30bbeca38d6578659919d4c3dc989ae18c16756690877fdc4dfa607f
`

could you use this as your env.

**Comment by ArpitaGanatra** [comment]
@WalterBlueu 

I went through my tutorial building the whole project from scratch reading the tutorial. 

I suggest you try the same, try to build a fresh project. please use the .env that I have provided to you above. I will try to add a video with the pizza.sol working example.

**Comment by WalterBlueu** [comment]
@ArpitaGanatra went back through it from scratch, using your .env file and the only issue I ran into was a solidity compiler version mismatch, which was easy enough to find and fix.  I was able to successfully deploy the contract!  Thank you for all of your support.  I am going to merge this pull request and promote this article.

**Comment by ArpitaGanatra** [comment]
@WalterBlueu Happy to help.
Let me know if you need help with anything else. :)

**Pull request merged**
