### PR TITLE
docs: truffle how to tutorial

### PR DESCRIPTION
**Pull request by menezesphill**

### CODE REVIEW

**Comment by WalterBlueu** [comment]
Hey @menezesphill I am going through the write up and ran into a snag.  I am getting this error while trying to list all XDC addresses bound to the mnemonic on truffle (the truffle console is not opening)

`
C:\Users\WalterBlueu\Pizza>truffle console --network xinfin
Error: Unknown arguments format passed to new HDWalletProvider. Please ensure you passed provider information along with either a mnemonic or private keys.
    at getOptions (C:\Users\WalterBlueu\Pizza\node_modules\@truffle\hdwallet-provider\src\constructor\getOptions.ts:144:11)
    at new HDWalletProvider (C:\Users\WalterBlueu\Pizza\node_modules\@truffle\hdwallet-provider\src\index.ts:74:19)
    at Object.provider (C:\Users\WalterBlueu\Pizza\truffle-config.js:10:23)
    at Object.getProvider (C:\Users\WalterBlueu\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\provider\index.js:20:1)
    at Object.create (C:\Users\WalterBlueu\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\provider\index.js:13:1)
    at TruffleConfig.get [as provider] (C:\Users\WalterBlueu\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\config\dist\configDefaults.js:275:1)
    at Object.detect (C:\Users\WalterBlueu\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\environment\environment.js:19:1)
    at Object.module.exports [as run] (C:\Users\WalterBlueu\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\console\run.js:29:1)
    at runCommand (C:\Users\WalterBlueu\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\command-utils.js:201:1)
Truffle v5.5.30 (core: 5.5.30)
Node v16.17.0

C:\Users\WalterBlueu\Pizza>
`

**Comment by menezesphill** [comment]
> Hey @menezesphill I am going through the write up and ran into a snag. I am getting this error while trying to list all XDC addresses bound to the mnemonic on truffle (the truffle console is not opening)

Ho there @WalterBlueu, there is a typo in the .env file, it reads:

```sh
mnemonoic
```

instead of

```sh
mnemonic
```

**Comment by WalterBlueu** [comment]
@menezesphill this is great, I have accepted the pull request and am going to close out the bounty and pay you

**Comment by WalterBlueu** [comment]
@menezesphill I am sending payment out now: $1,000 at $0.02643/XDC = 37836 XDC

**Comment by menezesphill** [comment]
Thank you, @WalterBlueu, my pleasure to help. Let me know if you want me to work on a different bounty (hardhat or REMIX). I didn't apply for those because I wanted to leave room for other bounty hunters.

**Comment by WalterBlueu** [comment]
@menezesphill we will be launching more bounties later today, please do check them out

**Pull request merged**
